(function() {var implementors = {};
implementors["modular_arithmetic"] = [{"text":"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> + <a class=\"trait\" href=\"modular_arithmetic/trait.Modulus.html\" title=\"trait modular_arithmetic::Modulus\">Modulus</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"modular_arithmetic/struct.FixedModular.html\" title=\"struct modular_arithmetic::FixedModular\">FixedModular</a>&lt;T&gt;","synthetic":false,"types":["modular_arithmetic::fixed_modular::FixedModular"]}];
implementors["problem051"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"problem051/struct.Template.html\" title=\"struct problem051::Template\">Template</a>","synthetic":false,"types":["problem051::Template"]}];
implementors["problem054"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"problem054/enum.Suit.html\" title=\"enum problem054::Suit\">Suit</a>","synthetic":false,"types":["problem054::Suit"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"problem054/enum.Rank.html\" title=\"enum problem054::Rank\">Rank</a>","synthetic":false,"types":["problem054::Rank"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"problem054/struct.Card.html\" title=\"struct problem054::Card\">Card</a>","synthetic":false,"types":["problem054::Card"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"problem054/enum.PokerHandType.html\" title=\"enum problem054::PokerHandType\">PokerHandType</a>","synthetic":false,"types":["problem054::PokerHandType"]}];
implementors["problem060"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"problem060/struct.PrimeSet.html\" title=\"struct problem060::PrimeSet\">PrimeSet</a>","synthetic":false,"types":["problem060::PrimeSet"]}];
implementors["problem078"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"problem078/struct.Mod.html\" title=\"struct problem078::Mod\">Mod</a>","synthetic":false,"types":["problem078::Mod"]}];
implementors["problem119"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"problem119/struct.Power.html\" title=\"struct problem119::Power\">Power</a>","synthetic":false,"types":["problem119::Power"]}];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()